services:
  - type: web
    name: it-hubb
    runtime: node
    region: singapore
    plan: free

    buildCommand: npm install && CI=false npm run build
    startCommand: node backend/index.js

    envVars:
      - key: NODE_ENV
        value: production

      - key: DB_URI
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: JWT_EXPIRES_TIME
        value: 7d

      - key: COOKIE_EXPIRES_TIME
        value: "7"

      - key: FRONTEND_URL
        sync: false

      - key: CLOUDINARY_CLOUD_NAME
        value: dwnmbbwjk

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

      - key: GOOGLE_CLIENT_ID
        value: 380365298782-rcvtvom4t2r8irtn3mpggeocco018t9m.apps.googleusercontent.com

      - key: SMTP_HOST
        value: sandbox.smtp.mailtrap.io

      - key: SMTP_PORT
        value: "2525"

      - key: SMTP_EMAIL
        sync: false

      - key: SMTP_PASSWORD
        sync: false

      - key: SMTP_FROM_EMAIL
        value: noreply@itshop.com

      - key: SMTP_FROM_NAME
        value: IT HUBB

      - key: VAPID_PUBLIC_KEY
        value: BN9DT5T3wxL8TyI6mAygCsZfBaZKJxmi0M6KKspRU6qQuJnLN_DpNYsUDn8_vxCWsKabKW6UryTDQ8NNzIWShRk

      - key: VAPID_PRIVATE_KEY
        sync: false

      - key: VAPID_SUBJECT
        value: mailto:noreply@itshop.com

      - key: BANK_TRANSFER_EXPIRY_MINUTES
        value: "15"

      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
